<?php
include_once("../config.php");

$pagegen = new page_gen();
$pagegen->round_to = 4;
$pagegen->start();

$s = new Game();
if (!$s->loggedIn || !$_GET['time']) {
    header("Location: index.php?");
    exit;
}

function h($value): string {
    return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8');
}

function fnum($value): string {
    return number_format((float)$value);
}

function renderInfoBlock(array $detail): void {
    echo '<div class="card full"><h4>Operational Brief</h4><p>' . h($detail['brief']) . '</p></div>';

    echo '<div class="card"><h4>Functions</h4><ul>';
    foreach (($detail['functions'] ?? []) as $item) {
        echo '<li>' . h($item) . '</li>';
    }
    echo '</ul></div>';

    echo '<div class="card"><h4>Features</h4><ul>';
    foreach (($detail['features'] ?? []) as $item) {
        echo '<li>' . h($item) . '</li>';
    }
    echo '</ul></div>';

    echo '<div class="card full"><h4>Logic & Rules</h4><ol>';
    foreach (($detail['logic'] ?? []) as $item) {
        echo '<li>' . h($item) . '</li>';
    }
    echo '</ol></div>';
}

function renderMechanicsMatrix(string $main, string $sub): void {
    $core = [
        'Turn cycle runs every 30 minutes and updates key production resources.',
        'Primary strategic resources are Naquadah, action turns, covert turns, and untrained units.',
        'Untrained units are generated by unit production and converted into military roles through training.',
    ];

    $race = [
        'Tauri focus: stronger attack posture.',
        'Goa\'uld focus: stronger income posture.',
        'Asgard focus: stronger defense posture.',
        'Replicator focus: stronger covert posture.',
    ];

    $byPage = [
        'operations:attack' => [
            'Attacks consume action turns and compare attacker offensive power against defender defensive power.',
            'Victory can transfer Naquadah from defender to attacker based on combat outcome.',
            'Anti-covert detachments may engage enemy covert forces during combat phases.',
        ],
        'operations:raid' => [
            'Raids focus on stealing untrained units instead of Naquadah.',
            'Raid missions are high tempo operations with elevated retaliation risk when overused.',
            'Repeated short-cycle raids should be monitored to avoid overextension and diplomatic blowback.',
        ],
        'operations:spy' => [
            'Spy missions consume covert turns, not regular attack turns.',
            'Failure can cost covert agents; success reveals enemy military and economy indicators.',
            'Covert vs anti-covert balance heavily influences reconnaissance reliability.',
        ],
        'operations:logs' => [
            'Logs are a tactical feedback loop for force composition and target quality.',
            'Reviewing losses by mission type helps adjust training and equipment priorities.',
            'Short debrief loops improve campaign consistency over long wars.',
        ],
        'military:fleet' => [
            'Mothership fleets support planet-oriented operations and offensive projection.',
            'Fleet strength can support attacks but does not act as home-planet defense in the same way.',
            'Fleet repair and bay investment should be planned with campaign timing.',
        ],
        'empire:planets' => [
            'Planet conquest commonly uses full mission expenditure and favors strong fleet posture.',
            'Planet acquisition is generally cadence-limited and should be timed around war objectives.',
            'Planet bonuses should be mapped to economy and military specialization plans.',
        ],
        'economy:banking' => [
            'Naquadah is the central purchase currency for units, equipment, and upgrades.',
            'Maintaining split reserves (on-hand and banked) improves shock resistance.',
            'Economic discipline sets the tempo for sustained military operations.',
        ],
        'economy:market' => [
            'Market turns and broker systems convert resources into strategic flexibility.',
            'Trade timing can materially change effective growth rates.',
            'Overtrading for one dimension can leave military or covert gaps.',
        ],
        'diplomacy:relations' => [
            'Relation stance affects war risk, coalition behavior, and target pressure.',
            'Stable stance policy across alliance members improves deterrence.',
            'Repeated actions against the same realm can trigger escalating political response.',
        ],
        'diplomacy:commander' => [
            'Commander chains shape protection structure and economic support flow.',
            'Support transfers should follow command objectives and risk posture.',
            'Leadership churn can reduce alliance execution quality.',
        ],
        'help:mechanics' => [
            'Covert sabotage doctrine often accepts lower losses on success and higher losses on failure.',
            'Mothership progression includes high-cost entry, bay expansion, and weapon specialization.',
            'Effective macro play balances production growth, intel quality, and turn efficiency.',
        ],
    ];

    $key = $main . ':' . $sub;
    $context = $byPage[$key] ?? [
        'This page participates in the 30-minute turn economy and shared resource model.',
        'Actions here should be sequenced with current action-turn, covert-turn, and Naquadah budget.',
        'Use this panel with logs and rankings to continually adjust doctrine.',
    ];

    echo '<div class="card full"><h4>Deep Mechanics Matrix</h4><ul>';
    foreach ($core as $line) {
        echo '<li>' . h($line) . '</li>';
    }
    echo '</ul></div>';

    echo '<div class="card"><h4>Race Meta Effects</h4><ul>';
    foreach ($race as $line) {
        echo '<li>' . h($line) . '</li>';
    }
    echo '</ul></div>';

    echo '<div class="card"><h4>Page-Specific Rules</h4><ul>';
    foreach ($context as $line) {
        echo '<li>' . h($line) . '</li>';
    }
    echo '</ul></div>';
}

function renderInteractiveCalculators(string $main, string $sub, $baseData, $personnel, $bank): void {
    if (($main === 'operations' && ($sub === 'attack' || $sub === 'raid')) || ($main === 'help' && $sub === 'mechanics')) {
        echo '<div class="card full">';
        echo '<h4>Battle Outcome Estimator</h4>';
        echo '<div class="calc-grid">';
        echo '<label>Attack Power<input id="calcAtkPower" type="number" min="0" value="' . h((int)($personnel->attackCount ?? 0)) . '"></label>';
        echo '<label>Defense Power<input id="calcDefPower" type="number" min="0" value="' . h((int)($personnel->defenseCount ?? 0)) . '"></label>';
        echo '<label>Attack Tech %<input id="calcAtkTech" type="number" min="0" value="12"></label>';
        echo '<label>Defense Tech %<input id="calcDefTech" type="number" min="0" value="12"></label>';
        echo '<label>Fleet Strength<input id="calcFleet" type="number" min="0" value="0"></label>';
        echo '<label>Shield/Planet Defense<input id="calcShield" type="number" min="0" value="0"></label>';
        echo '<label>Turns Committed<input id="calcTurns" type="number" min="1" max="15" value="10"></label>';
        echo '<label>Target Naquadah Pool<input id="calcNaqPool" type="number" min="0" value="1000000"></label>';
        echo '</div>';
        echo '<button class="calc-btn" type="button" onclick="(function(){var atk=Math.max(0,parseFloat(document.getElementById(\'calcAtkPower\').value)||0);var def=Math.max(0,parseFloat(document.getElementById(\'calcDefPower\').value)||0);var atkTech=Math.max(0,parseFloat(document.getElementById(\'calcAtkTech\').value)||0);var defTech=Math.max(0,parseFloat(document.getElementById(\'calcDefTech\').value)||0);var fleet=Math.max(0,parseFloat(document.getElementById(\'calcFleet\').value)||0);var shield=Math.max(0,parseFloat(document.getElementById(\'calcShield\').value)||0);var turns=Math.min(15,Math.max(1,parseFloat(document.getElementById(\'calcTurns\').value)||1));var naqPool=Math.max(0,parseFloat(document.getElementById(\'calcNaqPool\').value)||0);var atkScore=(atk*(1+atkTech/100))+fleet*0.35;var defScore=(def*(1+defTech/100))+shield*0.25;var ratio=atkScore/Math.max(defScore,1);var winChance=Math.max(5,Math.min(95,50+((ratio-1)*35)));var lootPct=Math.max(0.01,Math.min(0.25,0.03+Math.max(0,ratio-1)*0.1));var estLoot=naqPool*lootPct*(turns/15);document.getElementById(\'calcBattleOut\').innerHTML=\'Attack Score: \'+Math.round(atkScore).toLocaleString()+\' | Defense Score: \'+Math.round(defScore).toLocaleString()+\'<br>Win Chance: \'+winChance.toFixed(1)+\'% | Est. Naquadah Gain: \'+Math.round(estLoot).toLocaleString()+\'\';})();">Estimate Battle</button>';
        echo '<div id="calcBattleOut" class="calc-output">Adjust values and run estimate.</div>';
        echo '</div>';
    }

    if (($main === 'operations' && $sub === 'spy') || ($main === 'help' && $sub === 'mechanics')) {
        echo '<div class="card full">';
        echo '<h4>Covert Mission Estimator</h4>';
        echo '<div class="calc-grid">';
        echo '<label>Spies Sent<input id="calcSpySent" type="number" min="1" value="10000"></label>';
        echo '<label>Your Covert Tech %<input id="calcCovertTech" type="number" min="0" value="10"></label>';
        echo '<label>Enemy Anti-Covert Units<input id="calcEnemyAnti" type="number" min="0" value="8000"></label>';
        echo '<label>Enemy Anti-Covert Tech %<input id="calcEnemyAntiTech" type="number" min="0" value="10"></label>';
        echo '<label>Covert Turns Used<input id="calcCt" type="number" min="1" max="15" value="5"></label>';
        echo '</div>';
        echo '<button class="calc-btn" type="button" onclick="(function(){var spies=Math.max(1,parseFloat(document.getElementById(\'calcSpySent\').value)||1);var cTech=Math.max(0,parseFloat(document.getElementById(\'calcCovertTech\').value)||0);var enemy=Math.max(0,parseFloat(document.getElementById(\'calcEnemyAnti\').value)||0);var eTech=Math.max(0,parseFloat(document.getElementById(\'calcEnemyAntiTech\').value)||0);var ct=Math.min(15,Math.max(1,parseFloat(document.getElementById(\'calcCt\').value)||1));var covertPower=spies*(1+cTech/100)*Math.sqrt(ct/5);var antiPower=enemy*(1+eTech/100);var success=Math.max(2,Math.min(98,50+((covertPower-antiPower)/Math.max(antiPower,1))*40));var successLoss=spies*0.05;var failLoss=spies*0.50;var expectedLoss=(success/100)*successLoss+((100-success)/100)*failLoss;document.getElementById(\'calcCovertOut\').innerHTML=\'Success Chance: \'+success.toFixed(1)+\'%<br>Expected Spy Loss: \'+Math.round(expectedLoss).toLocaleString()+\' (Success ~5%, Failure ~50%)\';})();">Estimate Covert Mission</button>';
        echo '<div id="calcCovertOut" class="calc-output">Model includes SGW-style high failure penalties for covert actions.</div>';
        echo '</div>';
    }

    if (($main === 'economy' && ($sub === 'banking' || $sub === 'market' || $sub === 'production')) || ($main === 'help' && $sub === 'mechanics') || ($main === 'empire' && $sub === 'overview')) {
        echo '<div class="card full">';
        echo '<h4>Turn Economy Planner</h4>';
        echo '<div class="calc-grid">';
        echo '<label>Current On-Hand Naquadah<input id="calcCurrNaq" type="number" min="0" value="' . h((int)($bank->onHand ?? 0)) . '"></label>';
        echo '<label>Income Per Turn<input id="calcIncomeTurn" type="number" min="0" value="' . h((int)($baseData->income ?? 0)) . '"></label>';
        echo '<label>Current Untrained Units<input id="calcCurrUu" type="number" min="0" value="' . h((int)($personnel->uuCount ?? 0)) . '"></label>';
        echo '<label>Unit Production / Turn<input id="calcUpTurn" type="number" min="0" value="' . h((int)($baseData->up ?? 0)) . '"></label>';
        echo '<label>Planning Horizon (turns)<input id="calcHorizon" type="number" min="1" max="200" value="24"></label>';
        echo '</div>';
        echo '<button class="calc-btn" type="button" onclick="(function(){var naq=Math.max(0,parseFloat(document.getElementById(\'calcCurrNaq\').value)||0);var income=Math.max(0,parseFloat(document.getElementById(\'calcIncomeTurn\').value)||0);var uu=Math.max(0,parseFloat(document.getElementById(\'calcCurrUu\').value)||0);var up=Math.max(0,parseFloat(document.getElementById(\'calcUpTurn\').value)||0);var horizon=Math.min(200,Math.max(1,parseFloat(document.getElementById(\'calcHorizon\').value)||1));var projNaq=naq+(income*horizon);var projUu=uu+(up*horizon);var attackBudget=Math.floor(projNaq*0.35);var techBudget=Math.floor(projNaq*0.25);var reserveBudget=Math.floor(projNaq*0.20);document.getElementById(\'calcEcoOut\').innerHTML=\'Projected Naquadah: \'+Math.round(projNaq).toLocaleString()+\' | Projected UU: \'+Math.round(projUu).toLocaleString()+\'<br>Suggested Split -> Military: \'+attackBudget.toLocaleString()+\', Technology: \'+techBudget.toLocaleString()+\', Reserve: \'+reserveBudget.toLocaleString()+\'\';})();">Project Economy</button>';
        echo '<div id="calcEcoOut" class="calc-output">Use this to simulate turn-based growth and budget splits.</div>';
        echo '</div>';
    }
}

function renderFeatureWorkbenches(string $main, string $sub, $baseData, $personnel, $bank, $userStats, array $planets): void {
    if (($main === 'operations' && $sub === 'raid') || ($main === 'help' && $sub === 'mechanics')) {
        echo '<div class="card full">';
        echo '<h4>Raid Yield Planner</h4>';
        echo '<div class="calc-grid">';
        echo '<label>Enemy Untrained Units<input id="raidEnemyUu" type="number" min="0" value="120000"></label>';
        echo '<label>Raid Power<input id="raidPower" type="number" min="0" value="' . h((int)($personnel->attackCount ?? 0)) . '"></label>';
        echo '<label>Enemy Defense Power<input id="raidEnemyDef" type="number" min="0" value="90000"></label>';
        echo '<label>Turns Committed<input id="raidTurns" type="number" min="1" max="15" value="8"></label>';
        echo '</div>';
        echo '<button class="calc-btn" type="button" onclick="(function(){var enemyUU=Math.max(0,parseFloat(document.getElementById(\'raidEnemyUu\').value)||0);var rp=Math.max(0,parseFloat(document.getElementById(\'raidPower\').value)||0);var ed=Math.max(1,parseFloat(document.getElementById(\'raidEnemyDef\').value)||1);var turns=Math.min(15,Math.max(1,parseFloat(document.getElementById(\'raidTurns\').value)||1));var ratio=rp/ed;var success=Math.max(5,Math.min(95,45+((ratio-1)*40)));var stealPct=Math.max(0.01,Math.min(0.18,0.02+Math.max(0,ratio-1)*0.06));var estSteal=enemyUU*stealPct*(turns/15);var retaliation=Math.max(5,Math.min(95,55-((ratio-1)*20)+(turns*1.2)));document.getElementById(\'raidOut\').innerHTML=\'Raid Success Chance: \'+success.toFixed(1)+\'%<br>Estimated UU Captured: \'+Math.round(estSteal).toLocaleString()+\'<br>Retaliation Pressure Index: \'+retaliation.toFixed(1)+\'%\';})();">Estimate Raid</button>';
        echo '<div id="raidOut" class="calc-output">Use this planner to balance raid yield versus retaliation pressure.</div>';
        echo '</div>';
    }

    if (($main === 'operations' && $sub === 'spy') || ($main === 'intel' && $sub === 'reports') || ($main === 'help' && $sub === 'mechanics')) {
        echo '<div class="card full">';
        echo '<h4>Sabotage Impact Planner</h4>';
        echo '<div class="calc-grid">';
        echo '<label>Spies Sent<input id="sabSpies" type="number" min="1" value="15000"></label>';
        echo '<label>Your Covert Tech %<input id="sabTech" type="number" min="0" value="12"></label>';
        echo '<label>Enemy Anti-Covert Power<input id="sabEnemyAc" type="number" min="0" value="12000"></label>';
        echo '<label>Enemy Armory Size<input id="sabArmory" type="number" min="0" value="300000"></label>';
        echo '</div>';
        echo '<button class="calc-btn" type="button" onclick="(function(){var spies=Math.max(1,parseFloat(document.getElementById(\'sabSpies\').value)||1);var tech=Math.max(0,parseFloat(document.getElementById(\'sabTech\').value)||0);var enemy=Math.max(1,parseFloat(document.getElementById(\'sabEnemyAc\').value)||1);var armory=Math.max(0,parseFloat(document.getElementById(\'sabArmory\').value)||0);var covert=spies*(1+tech/100);var success=Math.max(2,Math.min(98,50+((covert-enemy)/enemy)*38));var damagePct=Math.max(0.01,Math.min(0.22,0.03+Math.max(0,success-50)/220));var estDamage=armory*damagePct;var expectedLoss=(success/100)*(spies*0.05)+((100-success)/100)*(spies*0.50);document.getElementById(\'sabOut\').innerHTML=\'Success Chance: \'+success.toFixed(1)+\'%<br>Estimated Armory Damage Index: \'+Math.round(estDamage).toLocaleString()+\'<br>Expected Spy Loss: \'+Math.round(expectedLoss).toLocaleString()+\'\';})();">Estimate Sabotage</button>';
        echo '<div id="sabOut" class="calc-output">Model follows high-risk covert doctrine with larger failure losses.</div>';
        echo '</div>';
    }

    if (($main === 'military' && $sub === 'fleet') || ($main === 'empire' && $sub === 'planets') || ($main === 'help' && $sub === 'mechanics')) {
        echo '<div class="card full">';
        echo '<h4>Planet Conquest Planner</h4>';
        echo '<div class="calc-grid">';
        echo '<label>Fleet Strength<input id="conqFleet" type="number" min="0" value="100000"></label>';
        echo '<label>Target Ground Defense<input id="conqDef" type="number" min="0" value="85000"></label>';
        echo '<label>Beacon Strength<input id="conqBeacon" type="number" min="0" value="100"></label>';
        echo '<label>Attempts Today<input id="conqAttempts" type="number" min="0" max="5" value="0"></label>';
        echo '</div>';
        echo '<button class="calc-btn" type="button" onclick="(function(){var fleet=Math.max(0,parseFloat(document.getElementById(\'conqFleet\').value)||0);var def=Math.max(1,parseFloat(document.getElementById(\'conqDef\').value)||1);var beacon=Math.max(0,parseFloat(document.getElementById(\'conqBeacon\').value)||0);var attempts=Math.max(0,parseFloat(document.getElementById(\'conqAttempts\').value)||0);var ratio=(fleet*(1+(beacon/1000)))/def;var success=Math.max(1,Math.min(97,42+((ratio-1)*45)));var blocked=attempts>=1;var fleetLossPct=Math.max(0.03,Math.min(0.45,0.20-(ratio-1)*0.08));if(blocked){document.getElementById(\'conqOut\').innerHTML=\'Daily limit reached: plan next conquest cycle (24h cadence).\';return;}document.getElementById(\'conqOut\').innerHTML=\'Conquest Success Chance: \'+success.toFixed(1)+\'%<br>Estimated Fleet Risk on Failure: \'+Math.round(fleetLossPct*100)+\'%<br>Reminder: conquest attempts are cadence-limited.\';})();">Estimate Conquest</button>';
        echo '<div id="conqOut" class="calc-output">Plan conquest around fleet risk, beacon context, and daily cadence limits.</div>';
        echo '</div>';
    }

    if (($main === 'diplomacy' && ($sub === 'relations' || $sub === 'alliance')) || ($main === 'help' && $sub === 'support')) {
        echo '<div class="card full">';
        echo '<h4>Diplomacy Policy Engine</h4>';
        echo '<div class="calc-grid">';
        echo '<label>Hits on Same Target (7d)<input id="dipHits" type="number" min="0" value="2"></label>';
        echo '<label>Raids on Same Target (7d)<input id="dipRaids" type="number" min="0" value="1"></label>';
        echo '<label>Alliance Tension Level (0-100)<input id="dipTension" type="number" min="0" max="100" value="35"></label>';
        echo '<label>Incoming Threat Index (0-100)<input id="dipThreat" type="number" min="0" max="100" value="40"></label>';
        echo '</div>';
        echo '<button class="calc-btn" type="button" onclick="(function(){var hits=Math.max(0,parseFloat(document.getElementById(\'dipHits\').value)||0);var raids=Math.max(0,parseFloat(document.getElementById(\'dipRaids\').value)||0);var tension=Math.max(0,Math.min(100,parseFloat(document.getElementById(\'dipTension\').value)||0));var threat=Math.max(0,Math.min(100,parseFloat(document.getElementById(\'dipThreat\').value)||0));var pressure=(hits*10)+(raids*12)+(tension*0.35)+(threat*0.4);var tier=\'Stable\';if(pressure>=95){tier=\'High Escalation\';}else if(pressure>=65){tier=\'Tense\';}else if(pressure>=40){tier=\'Watch\';}var recommendation=(tier===\'High Escalation\')?\'Pause repeat hits, coordinate alliance posture, open direct channel.\':(tier===\'Tense\')?\'Shift to selective targets, diversify operations, document incidents.\':(tier===\'Watch\')?\'Maintain spacing discipline, monitor retaliation signals.\':\'Proceed with standard posture and periodic review.\';document.getElementById(\'dipOut\').innerHTML=\'Policy Tier: \'+tier+\'<br>Escalation Score: \'+pressure.toFixed(1)+\'<br>Recommendation: \'+recommendation;})();">Evaluate Policy</button>';
        echo '<div id="dipOut" class="calc-output">Use this engine to avoid over-farming patterns and unnecessary alliance escalation.</div>';
        echo '</div>';
    }

    if (($main === 'economy' && $sub === 'technology') || ($main === 'economy' && $sub === 'production') || ($main === 'help' && $sub === 'mechanics')) {
        echo '<div class="card full">';
        echo '<h4>Upgrade ROI Workbench</h4>';
        echo '<div class="calc-grid">';
        echo '<label>Upgrade Cost (Naquadah)<input id="roiCost" type="number" min="0" value="500000"></label>';
        echo '<label>Extra Income / Turn<input id="roiIncome" type="number" min="0" value="15000"></label>';
        echo '<label>Extra UP / Turn<input id="roiUp" type="number" min="0" value="400"></label>';
        echo '<label>Horizon (turns)<input id="roiTurns" type="number" min="1" max="500" value="72"></label>';
        echo '</div>';
        echo '<button class="calc-btn" type="button" onclick="(function(){var cost=Math.max(0,parseFloat(document.getElementById(\'roiCost\').value)||0);var inc=Math.max(0,parseFloat(document.getElementById(\'roiIncome\').value)||0);var up=Math.max(0,parseFloat(document.getElementById(\'roiUp\').value)||0);var turns=Math.max(1,Math.min(500,parseFloat(document.getElementById(\'roiTurns\').value)||1));var valuePerUp=120;var gross=(inc*turns)+(up*valuePerUp*turns);var net=gross-cost;var payback=cost/Math.max((inc+(up*valuePerUp)),1);var verdict=(net>0)?\'Positive ROI\':\'Negative ROI\';document.getElementById(\'roiOut\').innerHTML=\'Projected Gross Value: \'+Math.round(gross).toLocaleString()+\'<br>Projected Net Value: \'+Math.round(net).toLocaleString()+\'<br>Payback: \'+payback.toFixed(1)+\' turns | Verdict: \'+verdict;})();">Run ROI</button>';
        echo '<div id="roiOut" class="calc-output">Compare upgrades by payback time before committing strategic reserves.</div>';
        echo '</div>';
    }

    if ($main === 'help' && $sub === 'glossary') {
        echo '<div class="card full">';
        echo '<h4>Command Abbreviations Table</h4>';
        echo '<table class="mini-table" border="0" width="100%">';
        echo '<tr><th align="left">Term</th><th align="left">Meaning</th></tr>';
        echo '<tr><td>AT</td><td>Attack Turns</td></tr>';
        echo '<tr><td>CT</td><td>Covert Turns</td></tr>';
        echo '<tr><td>MT</td><td>Market Turns</td></tr>';
        echo '<tr><td>UU</td><td>Untrained Units</td></tr>';
        echo '<tr><td>UP</td><td>Unit Production</td></tr>';
        echo '<tr><td>MS</td><td>Mothership</td></tr>';
        echo '<tr><td>TIP</td><td>Turn Income Produced</td></tr>';
        echo '<tr><td>RAL</td><td>Realm Alert Level</td></tr>';
        echo '</table>';
        echo '</div>';
    }

    if ($main === 'empire' && $sub === 'overview') {
        $planetCount = count($planets);
        echo '<div class="card full">';
        echo '<h4>Empire Operations Board</h4>';
        echo '<table class="mini-table" border="0" width="100%">';
        echo '<tr><th align="left">System</th><th align="left">Current State</th><th align="left">Recommended Focus</th></tr>';
        echo '<tr><td>Economy</td><td>On Hand: ' . fnum($bank->onHand ?? 0) . '</td><td>Maintain reserve and push market optimization</td></tr>';
        echo '<tr><td>Military</td><td>Army: ' . fnum($userStats->armySize ?? 0) . '</td><td>Balance offense/defense and covert ratios</td></tr>';
        echo '<tr><td>Production</td><td>UP/Turn: ' . fnum($baseData->up ?? 0) . '</td><td>Prioritize high ROI upgrades</td></tr>';
        echo '<tr><td>Territory</td><td>Planets: ' . fnum($planetCount) . '</td><td>Schedule conquest by fleet readiness</td></tr>';
        echo '</table>';
        echo '</div>';
    }
}

$main = isset($_GET['id']) ? preg_replace('/[^a-z]/', '', strtolower((string)$_GET['id'])) : 'empire';
$sub = isset($_GET['atype']) ? preg_replace('/[^a-z]/', '', strtolower((string)$_GET['atype'])) : '';

$mainTitles = [
    'empire' => 'Empire Command',
    'military' => 'Military Directorate',
    'operations' => 'Operations Center',
    'economy' => 'Economic Network',
    'diplomacy' => 'Diplomacy Office',
    'intel' => 'Intelligence Bureau',
    'community' => 'Community & Updates',
    'help' => 'Guides & Help Desk',
];

$subDefaults = [
    'empire' => 'overview',
    'military' => 'personnel',
    'operations' => 'attack',
    'economy' => 'banking',
    'diplomacy' => 'alliance',
    'intel' => 'rankings',
    'community' => 'forums',
    'help' => 'newplayer',
];

$subLabels = [
    'empire' => ['overview' => 'Overview', 'planets' => 'Planets', 'command' => 'Command', 'progress' => 'Progression'],
    'military' => ['personnel' => 'Personnel', 'armory' => 'Armory', 'training' => 'Training', 'fleet' => 'Fleet'],
    'operations' => ['attack' => 'Attack', 'raid' => 'Raid', 'spy' => 'Spy', 'logs' => 'Combat Logs'],
    'economy' => ['banking' => 'Banking', 'market' => 'Market', 'technology' => 'Technology', 'production' => 'Production'],
    'diplomacy' => ['alliance' => 'Alliance', 'relations' => 'Relations', 'messages' => 'Messages', 'commander' => 'Commander Chain'],
    'intel' => ['rankings' => 'Rankings', 'reports' => 'Battle Reports', 'threats' => 'Threat Matrix', 'map' => 'Sector Map'],
    'community' => ['forums' => 'Forums', 'updates' => 'Updates', 'contact' => 'Contact', 'faq' => 'FAQ'],
    'help' => ['newplayer' => 'New Player', 'mechanics' => 'Mechanics', 'glossary' => 'Glossary', 'support' => 'Support'],
];

$systemDetails = [
    'empire' => [
        'overview' => [
            'brief' => 'Central empire dashboard showing economy, army growth, and strategic readiness.',
            'functions' => ['View economy and production snapshots', 'Open base, technology, and progress modules', 'Track current military scale'],
            'features' => ['Live stat panel', 'Quick action shortcuts', 'Command feed compatible'],
            'logic' => ['Income and production are turn-based values', 'Army size updates from unit tables', 'Treasury values pull from bank and hand balances'],
        ],
        'planets' => [
            'brief' => 'Planet registry for territory visibility and expansion planning.',
            'functions' => ['List discovered planets', 'Show size and bonus metadata', 'Support growth path planning'],
            'features' => ['Table view for ownership info', 'Safe empty-state messaging', 'Integrated with empire context'],
            'logic' => ['Planet rows are loaded per player id', 'No planets returns an informative fallback', 'Bonuses act as strategic specialization signals'],
        ],
        'command' => [
            'brief' => 'Displays command structure and leadership chain context.',
            'functions' => ['Show commander and rank context', 'Jump to diplomacy relations', 'Open alliance roster tools'],
            'features' => ['Leadership summary card', 'Diplomacy shortcuts', 'Alliance workflow links'],
            'logic' => ['Commander relationship affects coordination flow', 'Race and rank influence strategic role', 'Diplomacy actions are profile-driven'],
        ],
        'progress' => [
            'brief' => 'Progression panel for growth priorities and expansion sequencing.',
            'functions' => ['Open progress dashboard', 'Present upgrade priorities', 'Guide scaling decisions'],
            'features' => ['Priority list', 'Module deep-link', 'Growth strategy guidance'],
            'logic' => ['Higher UP increases military velocity', 'Planet capacity lifts macro growth ceiling', 'Economic stability supports sustained warfare'],
        ],
    ],
    'military' => [
        'personnel' => [
            'brief' => 'Military personnel composition and combat role distribution.',
            'functions' => ['Break down unit classes', 'Expose untrained reserve depth', 'Guide training allocation'],
            'features' => ['Role-by-role unit table', 'Readable totals', 'Linked to training decisions'],
            'logic' => ['Untrained units are conversion input', 'Role balance impacts attack/defense outcomes', 'Covert and anti-covert stats affect intel warfare'],
        ],
        'armory' => [
            'brief' => 'Equipment readiness and force amplification center.',
            'functions' => ['Open armory controls', 'Tune loadout direction', 'Prepare for mission types'],
            'features' => ['Armory quick-link', 'Readiness briefing', 'Battle prep guidance'],
            'logic' => ['Equipment investment alters combat effectiveness', 'Balanced loadouts reduce tactical gaps', 'Repairs preserve long-term force value'],
        ],
        'training' => [
            'brief' => 'Unit conversion operations from reserve to specialized roles.',
            'functions' => ['Open train and untrain modules', 'Shift force composition', 'Adjust to campaign needs'],
            'features' => ['Dual workflow for train/untrain', 'Fast operational links', 'Role conversion guidance'],
            'logic' => ['Training spends reserves into active roles', 'Untraining restores flexibility at a tradeoff', 'Composition changes should follow mission forecasts'],
        ],
        'fleet' => [
            'brief' => 'Fleet mobility and deployment readiness control.',
            'functions' => ['Open fleet dock', 'Coordinate movement posture', 'Stage force projection'],
            'features' => ['Dock entry shortcut', 'Deployment guidance', 'Readiness framing'],
            'logic' => ['Fleet positioning influences reaction speed', 'Readiness windows affect mission timing', 'Sustained operations require economy support'],
        ],
    ],
    'operations' => [
        'attack' => [
            'brief' => 'Direct strike planning and hostile target engagement.',
            'functions' => ['Open target ranking list', 'Select enemy profiles', 'Initiate offensive planning'],
            'features' => ['Targeting jump-link', 'Mission overview', 'Engagement staging cues'],
            'logic' => ['Attacks consume action turns', 'Outcome quality depends on force matchups', 'Intel prior to strike reduces risk'],
        ],
        'raid' => [
            'brief' => 'Fast resource extraction missions against exposed opponents.',
            'functions' => ['Plan high-speed raids', 'Identify weaker logistics targets', 'Cycle opportunistic operations'],
            'features' => ['Raid doctrine guidance', 'Risk-reward framing', 'Quick mission context'],
            'logic' => ['Raids prioritize economy disruption', 'Repeated raids raise retaliation probability', 'Execution cadence must respect turn budget'],
        ],
        'spy' => [
            'brief' => 'Covert intelligence collection and pre-war reconnaissance.',
            'functions' => ['Open spy module', 'Gather enemy indicators', 'Validate strike assumptions'],
            'features' => ['Spy workflow shortcut', 'Recon brief', 'Counter-risk planning cues'],
            'logic' => ['Covert success depends on role strength', 'Anti-covert defenses reduce penetration', 'Intel quality drives mission confidence'],
        ],
        'logs' => [
            'brief' => 'Post-operation analysis and outcome review center.',
            'functions' => ['Open combat logs', 'Review mission outcomes', 'Refine strategic doctrine'],
            'features' => ['Action history access', 'Debrief framing', 'Feedback loop support'],
            'logic' => ['Historical outcomes reveal matchup patterns', 'Loss analysis informs retraining', 'Frequent review improves tactical consistency'],
        ],
    ],
    'economy' => [
        'banking' => [
            'brief' => 'Treasury management for liquidity, safety, and war funding.',
            'functions' => ['Show on-hand and banked resources', 'Open bank module', 'Guide reserve strategy'],
            'features' => ['Dual-balance view', 'Direct bank access', 'Funding policy hints'],
            'logic' => ['On-hand funds support immediate actions', 'Banked funds protect longer-term reserves', 'Liquidity planning stabilizes campaign pacing'],
        ],
        'market' => [
            'brief' => 'Resource trade hub for economic optimization.',
            'functions' => ['Open market', 'Adjust resource mix', 'Capture trade opportunities'],
            'features' => ['Market shortcut', 'Trade operation context', 'Economy tuning support'],
            'logic' => ['Market timing affects purchasing power', 'Overextension can starve military spending', 'Balanced trading smooths growth volatility'],
        ],
        'technology' => [
            'brief' => 'Research and development for systemic empire scaling.',
            'functions' => ['Open technology tree', 'Prioritize upgrades', 'Improve combat and economy efficiency'],
            'features' => ['Tech module link', 'Upgrade planning overview', 'Cross-system growth context'],
            'logic' => ['Technology compounds over time', 'Research priorities should reflect strategy', 'Early economic tech often improves long-term tempo'],
        ],
        'production' => [
            'brief' => 'Production doctrine for army throughput and mining momentum.',
            'functions' => ['Advise UP investments', 'Balance miners and combat roles', 'Protect economic infrastructure'],
            'features' => ['Doctrine checklist', 'Scale-up guidance', 'Force-economy balance prompts'],
            'logic' => ['UP directly affects unit generation', 'Over-militarization can stall growth', 'Defensive coverage preserves production gains'],
        ],
    ],
    'diplomacy' => [
        'alliance' => [
            'brief' => 'Alliance coordination and bloc-level strategic organization.',
            'functions' => ['Open alliance roster', 'Coordinate member roles', 'Manage coalition focus'],
            'features' => ['Roster link', 'Coordination framing', 'Team strategy context'],
            'logic' => ['Alliance structure increases strategic reach', 'Role clarity reduces operational friction', 'Collective response deters opportunistic attacks'],
        ],
        'relations' => [
            'brief' => 'Inter-empire stance management for peace and conflict control.',
            'functions' => ['Set relation stance', 'Review profile-based options', 'Signal diplomatic intent'],
            'features' => ['Profile action shortcut', 'Stance guidance', 'Conflict-state awareness'],
            'logic' => ['Relations influence engagement probability', 'Hostile posture raises military pressure', 'Clear stance policy supports alliance coherence'],
        ],
        'messages' => [
            'brief' => 'Secure communication channel for diplomacy and operations.',
            'functions' => ['Open inbox', 'Coordinate operations', 'Exchange strategic updates'],
            'features' => ['Messaging link', 'Diplomatic communication scope', 'Operational syncing support'],
            'logic' => ['Fast communication improves response time', 'Message clarity reduces coordination errors', 'Thread discipline preserves audit context'],
        ],
        'commander' => [
            'brief' => 'Commander assignment and support-chain administration.',
            'functions' => ['Open commander tools', 'Manage parent chain context', 'Support command transfer workflows'],
            'features' => ['Commander shortcut', 'Chain visibility cues', 'Support-flow alignment'],
            'logic' => ['Command chain affects organizational flow', 'Support transfers should match hierarchy goals', 'Leadership stability improves campaign execution'],
        ],
    ],
    'intel' => [
        'rankings' => [
            'brief' => 'Global standings for threat assessment and target selection.',
            'functions' => ['Open rankings', 'Track rival growth', 'Discover trend changes'],
            'features' => ['Rank console link', 'Comparative visibility', 'Trend awareness'],
            'logic' => ['Rapid rank gain can indicate power spikes', 'Rank brackets can guide target difficulty', 'Ranking deltas inform risk posture'],
        ],
        'reports' => [
            'brief' => 'Mission report intelligence for operational quality control.',
            'functions' => ['Open action reports', 'Review losses and gains', 'Update mission tactics'],
            'features' => ['Report module link', 'Outcome-focused analysis flow', 'Decision feedback loop'],
            'logic' => ['Consistent report review improves efficiency', 'Loss patterns reveal composition issues', 'Action context supports tactical iteration'],
        ],
        'threats' => [
            'brief' => 'Threat matrix for hostile indicators and escalation risk.',
            'functions' => ['Surface key danger signals', 'Highlight hostile patterns', 'Guide defensive posture'],
            'features' => ['Risk checklist', 'Strategic warning panel', 'Escalation awareness'],
            'logic' => ['Repeated raid contact increases conflict probability', 'Hostile command chains can signal coalition pressure', 'Nearby growth spikes can shift regional balance'],
        ],
        'map' => [
            'brief' => 'Sector-level influence estimation using profile intelligence.',
            'functions' => ['Frame territory influence zones', 'Correlate race/rank/alliance data', 'Support expansion route planning'],
            'features' => ['Strategic mapping brief', 'Influence modeling hints', 'Expansion planning context'],
            'logic' => ['Influence follows power and alliance concentration', 'Regional pressure informs defensive placements', 'Map intelligence should be updated from fresh scans'],
        ],
    ],
    'community' => [
        'forums' => [
            'brief' => 'Community collaboration space for strategy and social coordination.',
            'functions' => ['Open forum portal', 'Join public discussions', 'Share strategic insights'],
            'features' => ['External forum link', 'Community visibility', 'Knowledge exchange channel'],
            'logic' => ['Shared intelligence can improve alliance performance', 'Public posts can reveal intent if overexposed', 'Community participation strengthens retention'],
        ],
        'updates' => [
            'brief' => 'Patch and balance awareness panel for meta adaptation.',
            'functions' => ['Open updates/faq', 'Read change notes', 'Adjust strategic priorities'],
            'features' => ['Update feed access', 'Meta-change visibility', 'Balance tracking support'],
            'logic' => ['Patch notes can shift optimal builds', 'Early adaptation yields competitive edge', 'Tracking updates reduces strategic drift'],
        ],
        'contact' => [
            'brief' => 'Staff communication lane for moderation and support routing.',
            'functions' => ['Open messaging channel', 'Report operational issues', 'Coordinate moderator follow-up'],
            'features' => ['Contact pathway shortcut', 'Escalation guidance', 'Support routing context'],
            'logic' => ['Clear issue details reduce resolution time', 'Timestamped reports improve traceability', 'Proper channel use preserves support workflow'],
        ],
        'faq' => [
            'brief' => 'Rules and common answers to reduce onboarding friction.',
            'functions' => ['Open FAQ module', 'Review core policies', 'Understand progression norms'],
            'features' => ['Policy and guidance access', 'Beginner-friendly references', 'Rule clarification hub'],
            'logic' => ['Rule knowledge prevents avoidable penalties', 'Policy alignment improves community health', 'Frequent FAQ review reduces repeated errors'],
        ],
    ],
    'help' => [
        'newplayer' => [
            'brief' => 'Step-by-step early game launch sequence for stable growth.',
            'functions' => ['Outline opening priorities', 'Guide safe expansion rhythm', 'Reduce beginner misplays'],
            'features' => ['Ordered launch checklist', 'Beginner strategy framing', 'Resource safety guidance'],
            'logic' => ['Balanced training lowers early vulnerability', 'Reserve funds protect against shocks', 'Scouting before attack improves odds'],
        ],
        'mechanics' => [
            'brief' => 'Core systems summary explaining turns, combat, and scaling.',
            'functions' => ['Explain action turn economy', 'Highlight combat score impact', 'Describe tech and support rules'],
            'features' => ['Mechanics bullet reference', 'System relationship clarity', 'Practical doctrine hints'],
            'logic' => ['Offensive actions are turn-gated', 'Military score influences ranking pressure', 'Transfer and growth systems reward planning discipline'],
        ],
        'glossary' => [
            'brief' => 'Terminology reference for all key game concepts.',
            'functions' => ['Define core resources', 'Clarify command-chain terms', 'Support quick interpretation'],
            'features' => ['Keyword definitions', 'Fast lookup format', 'New player comprehension support'],
            'logic' => ['Common vocabulary reduces coordination errors', 'Shared terminology improves alliance execution', 'Concept clarity supports faster decision cycles'],
        ],
        'support' => [
            'brief' => 'Issue reporting protocol for account and gameplay incidents.',
            'functions' => ['Provide support reporting guidance', 'Direct users to contact channels', 'Improve issue triage quality'],
            'features' => ['Support workflow brief', 'Evidence checklist cues', 'Escalation context'],
            'logic' => ['Detailed reports are resolved faster', 'Including players and timestamps improves verification', 'Channel discipline prevents lost requests'],
        ],
    ],
];

if (!isset($mainTitles[$main])) {
    $main = 'empire';
}
if ($sub === '' || !isset($subLabels[$main][$sub])) {
    $sub = $subDefaults[$main];
}

$uid = (int)$_SESSION['userid'];
$s->updatePower($uid);

$baseData = $s->baseVars();
$personnel = $s->getPersonnel($uid);
$bank = $s->bank();
$userStats = $s->getUserInfo($uid);
$planets = $s->getUserPlanets($uid);

$title = $mainTitles[$main];
$subTitle = $subLabels[$main][$sub];

echo '<div class="page-hub">';
echo '<div class="page-hub-head">';
echo '<h3>' . h($title) . ' - ' . h($subTitle) . '</h3>';
echo '<p>Page: ' . h($main) . ' / ' . h($sub) . ' | Player: ' . h($_SESSION['username']) . '</p>';
echo '</div>';

echo '<div class="page-subnav">';
foreach ($subLabels[$main] as $subKey => $subName) {
    $activeClass = ($subKey === $sub) ? ' class="active"' : '';
    echo '<a' . $activeClass . ' href="javascript:void(0)" onclick="sendData(\'pages\',\'get\',\'' . h($main) . '\',\'' . h($subKey) . '\'); return false">' . h($subName) . '</a>';
}
echo '</div>';

echo '<div class="page-grid">';

if ($main === 'empire' && $sub === 'overview') {
    echo '<div class="card"><h4>Empire Snapshot</h4>';
    echo '<p><strong>Army Size:</strong> ' . fnum($userStats->armySize ?? 0) . '</p>';
    echo '<p><strong>Treasury:</strong> ' . fnum($bank->onHand ?? 0) . ' Naquadah</p>';
    echo '<p><strong>Income/Turn:</strong> ' . fnum($baseData->income ?? 0) . '</p>';
    echo '<p><strong>Unit Production:</strong> ' . fnum($baseData->up ?? 0) . '</p>';
    echo '</div>';
    echo '<div class="card"><h4>Quick Actions</h4>';
    echo '<p><a href="javascript:void(0)" onclick="sendData(\'base\',\'get\',\'mainDisplay\'); return false">Open Base Module</a></p>';
    echo '<p><a href="javascript:void(0)" onclick="sendData(\'technology\',\'get\',\'mainDisplay\'); return false">Open Technology</a></p>';
    echo '<p><a href="javascript:void(0)" onclick="sendData(\'progress\',\'get\',\'mainDisplay\'); return false">Open Progress</a></p>';
    echo '</div>';
}

if ($main === 'empire' && $sub === 'planets') {
    echo '<div class="card full"><h4>Planet Registry</h4>';
    if (count($planets) === 0) {
        echo '<p>No planets discovered in your registry yet.</p>';
    } else {
        echo '<table width="100%" border="0"><tr><th align="left">Planet</th><th align="left">Size</th><th align="left">Bonus</th></tr>';
        foreach ($planets as $planet) {
            echo '<tr><td>' . h($planet['name']) . '</td><td>' . h($planet['size']) . '</td><td>' . h($planet['bonus']) . '</td></tr>';
        }
        echo '</table>';
    }
    echo '</div>';
}

if ($main === 'empire' && $sub === 'command') {
    echo '<div class="card"><h4>Command Chain</h4>';
    echo '<p><strong>Commander:</strong> ' . h($userStats->cmdrName ?? 'None') . '</p>';
    echo '<p><strong>Race:</strong> ' . h($userStats->race ?? '') . '</p>';
    echo '<p><strong>Rank:</strong> ' . h($userStats->rank ?? '') . '</p>';
    echo '</div>';
    echo '<div class="card"><h4>Diplomatic Actions</h4>';
    echo '<p><a href="javascript:void(0)" onclick="sendData(\'pages\',\'get\',\'diplomacy\',\'relations\'); return false">Manage Relations</a></p>';
    echo '<p><a href="javascript:void(0)" onclick="sendData(\'ally_mlist\',\'get\',\'mainDisplay\'); return false">Alliance Member List</a></p>';
    echo '</div>';
}

if ($main === 'empire' && $sub === 'progress') {
    echo '<div class="card"><h4>Progress Status</h4>';
    echo '<p>Track your expansion level, unit production growth, and military readiness.</p>';
    echo '<p><a href="javascript:void(0)" onclick="sendData(\'progress\',\'get\',\'mainDisplay\'); return false">Open Progress Dashboard</a></p>';
    echo '</div>';
    echo '<div class="card"><h4>Upgrade Priorities</h4>';
    echo '<ul><li>Increase Unit Production</li><li>Expand Planet Capacity</li><li>Boost Economy/Turn</li></ul>';
    echo '</div>';
}

if ($main === 'military') {
    if ($sub === 'personnel') {
        echo '<div class="card full"><h4>Personnel Breakdown</h4>';
        echo '<table width="100%" border="0">';
        echo '<tr><td>Untrained Units</td><td>' . fnum($personnel->uuCount ?? 0) . '</td></tr>';
        echo '<tr><td>Attack Units</td><td>' . fnum($personnel->attackCount ?? 0) . '</td></tr>';
        echo '<tr><td>Defense Units</td><td>' . fnum($personnel->defenseCount ?? 0) . '</td></tr>';
        echo '<tr><td>Covert Units</td><td>' . fnum($personnel->covertCount ?? 0) . '</td></tr>';
        echo '<tr><td>Anti-Covert Units</td><td>' . fnum($personnel->anticovertCount ?? 0) . '</td></tr>';
        echo '</table>';
        echo '</div>';
    }
    if ($sub === 'armory') {
        echo '<div class="card"><h4>Armory Control</h4><p>Manage attack/defense equipment loadouts and repair weapons.</p><p><a href="javascript:void(0)" onclick="sendData(\'armory\',\'get\',\'mainDisplay\'); return false">Open Armory</a></p></div>';
    }
    if ($sub === 'training') {
        echo '<div class="card"><h4>Training Command</h4><p>Convert untrained units into combat-ready specialists.</p><p><a href="javascript:void(0)" onclick="sendData(\'train\',\'get\',\'mainDisplay\'); return false">Open Training</a></p></div>';
        echo '<div class="card"><h4>Demobilization</h4><p>Reverse assignments when strategy shifts.</p><p><a href="javascript:void(0)" onclick="sendData(\'untrain\',\'get\',\'mainDisplay\'); return false">Open Untrain</a></p></div>';
    }
    if ($sub === 'fleet') {
        echo '<div class="card"><h4>Fleet Operations</h4><p>Deploy, reposition, and monitor fleet readiness.</p><p><a href="javascript:void(0)" onclick="sendData(\'fleetdock\',\'get\',\'mainDisplay\'); return false">Open Fleet Dock</a></p></div>';
    }
}

if ($main === 'operations') {
    if ($sub === 'attack') {
        echo '<div class="card"><h4>Attack Missions</h4><p>Launch direct strikes against enemy empires.</p><p><a href="javascript:void(0)" onclick="sendData(\'rank\',\'get\',\'mainDisplay\'); return false">Select Targets</a></p></div>';
    }
    if ($sub === 'raid') {
        echo '<div class="card"><h4>Raid Missions</h4><p>Execute high-speed resource raids for rapid gains.</p><p>Use player profiles to trigger raid actions.</p></div>';
    }
    if ($sub === 'spy') {
        echo '<div class="card"><h4>Spy Network</h4><p>Gather intel before committing forces.</p><p><a href="javascript:void(0)" onclick="sendData(\'spy\',\'get\',\'mainDisplay\'); return false">Open Spy Module</a></p></div>';
    }
    if ($sub === 'logs') {
        echo '<div class="card"><h4>Combat Logs</h4><p>Review outcomes and refine strategy.</p><p><a href="javascript:void(0)" onclick="sendData(\'logs\',\'get\',\'mainDisplay\'); return false">Open Logs</a></p></div>';
    }
}

if ($main === 'economy') {
    if ($sub === 'banking') {
        echo '<div class="card"><h4>Banking Control</h4>';
        echo '<p><strong>On Hand:</strong> ' . fnum($bank->onHand ?? 0) . '</p>';
        echo '<p><strong>In Bank:</strong> ' . fnum($bank->inBank ?? 0) . '</p>';
        echo '<p><a href="javascript:void(0)" onclick="sendData(\'bank\',\'get\',\'mainDisplay\'); return false">Open Bank Module</a></p>';
        echo '</div>';
    }
    if ($sub === 'market') {
        echo '<div class="card"><h4>Market Trade</h4><p>Buy and sell resources to tune your economy.</p><p><a href="javascript:void(0)" onclick="sendData(\'market\',\'get\',\'mainDisplay\'); return false">Open Market</a></p></div>';
    }
    if ($sub === 'technology') {
        echo '<div class="card"><h4>Technology Tree</h4><p>Advance economy, combat, and covert capabilities.</p><p><a href="javascript:void(0)" onclick="sendData(\'technology\',\'get\',\'mainDisplay\'); return false">Open Technology</a></p></div>';
    }
    if ($sub === 'production') {
        echo '<div class="card"><h4>Production Planning</h4><p>Focus on unit production and mining throughput to scale your empire.</p><ul><li>Upgrade UP first for faster growth</li><li>Balance miners vs combat readiness</li><li>Protect income assets with defense</li></ul></div>';
    }
}

if ($main === 'diplomacy') {
    if ($sub === 'alliance') {
        echo '<div class="card"><h4>Alliance Management</h4><p>Coordinate allies, officer chains, and power blocs.</p><p><a href="javascript:void(0)" onclick="sendData(\'ally_mlist\',\'get\',\'mainDisplay\'); return false">Open Alliance Roster</a></p></div>';
    }
    if ($sub === 'relations') {
        echo '<div class="card"><h4>Relations Desk</h4><p>Set war, neutral, and peace stances with other empires through player profile actions.</p><p><a href="javascript:void(0)" onclick="sendData(\'user\',\'get\',\'' . $uid . '\'); return false">Open Profile Actions</a></p></div>';
    }
    if ($sub === 'messages') {
        echo '<div class="card"><h4>Secure Messaging</h4><p>Send diplomatic messages and coordinate attacks.</p><p><a href="javascript:void(0)" onclick="sendData(\'messages\',\'get\',\'mainDisplay\'); return false">Open Inbox</a></p></div>';
    }
    if ($sub === 'commander') {
        echo '<div class="card"><h4>Commander Chain</h4><p>Assign commanders and issue support transfers from player profile pages.</p><p><a href="javascript:void(0)" onclick="sendData(\'user\',\'get\',\'' . $uid . '\'); return false">Open Commander Tools</a></p></div>';
    }
}

if ($main === 'intel') {
    if ($sub === 'rankings') {
        echo '<div class="card"><h4>Rankings Console</h4><p>Monitor global power standings and rival growth.</p><p><a href="javascript:void(0)" onclick="sendData(\'rank\',\'get\',\'mainDisplay\'); return false">Open Rankings</a></p></div>';
    }
    if ($sub === 'reports') {
        echo '<div class="card"><h4>Battle Reports</h4><p>Digest mission outcomes and casualty analytics.</p><p><a href="javascript:void(0)" onclick="sendData(\'actionLogs\',\'get\',\'mainDisplay\'); return false">Open Action Reports</a></p></div>';
    }
    if ($sub === 'threats') {
        echo '<div class="card"><h4>Threat Matrix</h4><p>High threat indicators:</p><ul><li>Rapid rank ascension nearby</li><li>Hostile commander chains</li><li>Repeated raid contact</li></ul></div>';
    }
    if ($sub === 'map') {
        echo '<div class="card"><h4>Sector Map</h4><p>Use race, rank, and alliance data from profile scans to map influence zones.</p></div>';
    }
}

if ($main === 'community') {
    if ($sub === 'forums') {
        echo '<div class="card"><h4>Forums</h4><p>Join strategy discussions, diplomacy talks, and event threads.</p><p><a href="forums/" target="_blank">Open Forums</a></p></div>';
    }
    if ($sub === 'updates') {
        echo '<div class="card"><h4>Update Feed</h4><p>Read update announcements and balancing notes.</p><p><a href="javascript:void(0)" onclick="sendData(\'faq\',\'get\',\'mainDisplay\'); return false">Open News/FAQ</a></p></div>';
    }
    if ($sub === 'contact') {
        echo '<div class="card"><h4>Contact Command</h4><p>Reach moderators and administrators through in-game messaging channels.</p><p><a href="javascript:void(0)" onclick="sendData(\'messages\',\'get\',\'mainDisplay\'); return false">Open Messaging</a></p></div>';
    }
    if ($sub === 'faq') {
        echo '<div class="card"><h4>FAQ</h4><p>Core rules, policy, and progression advice are available here.</p><p><a href="javascript:void(0)" onclick="sendData(\'faq\',\'get\',\'mainDisplay\'); return false">Open FAQ</a></p></div>';
    }
}

if ($main === 'help') {
    if ($sub === 'newplayer') {
        echo '<div class="card full"><h4>New Player Launch Plan</h4><ol><li>Train a balanced starter army from untrained units.</li><li>Keep a reserve of Naquadah for emergency retraining.</li><li>Upgrade production before expensive wars.</li><li>Scout targets before every major operation.</li></ol></div>';
    }
    if ($sub === 'mechanics') {
        echo '<div class="card"><h4>Core Mechanics</h4><ul><li>Action turns gate all offensive actions.</li><li>Military score influences rank and combat outcomes.</li><li>1% broker fee applies to support transfers.</li><li>Technology upgrades scale growth and resilience.</li></ul></div>';
    }
    if ($sub === 'glossary') {
        echo '<div class="card"><h4>Glossary</h4><p><strong>Naquadah:</strong> Main currency.</p><p><strong>UP:</strong> Unit production per turn.</p><p><strong>Commander:</strong> Parent node in command chain.</p><p><strong>Action Turn:</strong> Strategic action resource.</p></div>';
    }
    if ($sub === 'support') {
        echo '<div class="card"><h4>Support Desk</h4><p>For account issues, use in-game contact and community channels. Include mission timestamps and affected players in reports.</p></div>';
    }
}

if (isset($systemDetails[$main][$sub])) {
    renderInfoBlock($systemDetails[$main][$sub]);
}

renderMechanicsMatrix($main, $sub);
renderInteractiveCalculators($main, $sub, $baseData, $personnel, $bank);
renderFeatureWorkbenches($main, $sub, $baseData, $personnel, $bank, $userStats, $planets);

echo '</div>';
echo '</div>';

echo "Query Count: " . $s->queryCount . "<br>";
$pagegen->stop();
print('page generation time: ' . $pagegen->gen());
?>